### ISSUE TITLE
Come up with a way to map the website YAML to app JSON

### ISSUE THREAD

**Issue by mdiasdev** [SwiftFest/ios_app#18]
We need a way to sync the content from the website's YAML as hardcoded JSON in the app

**Comment by ZevEisenberg** [comment]
swiftfest.io/speakers.json
swiftfest.io/schedule.json
swiftfest.io/sessions.json

These should have everything you need, and they’re automatically regenerated when the site is compiled so they’re always up to date. Let me know if you want something changed.

**Comment by SeanROlszewski** [comment]
Awesome. Thank you!
